/**
 * NOMENCLATURAS Y CLASIFICACIÓN DE CONSTANTES (AT)
 *
 * Prefijo AT: Relativo a Autenticación.
 *
 * Notación general: AT_{sufijo}
 */

/* Tabla de roles */

export const AT_ROLES = {
    DEV: 1, // DESAROLLADOR DE INFORMÁTICA
    ARA_JEFE: 2, // JEFE DE UNIDAD ASOCIADA A GESTIÓN DE ARANCELES
    ARA_ADMINISTRADOR: 3, // ADMINISTRADOR UNIDAD DE ASOCIADA A GESTIÓN DE ARANCELES
    ARA_ANALISTA: 4, // ANALISTA DE UNIDAD ASOCIADA A GESTIÓN DE ARANCELES
    DACE: 5, // DIRECCIÓN DE ADMISIÓN Y CONTROL DE ESTUDIOS
    SEC_GEN: 6, // SECRETARÍA GENERAL DEL RECTORADO
    REG_CON: 7, // REGISTRO Y CONTROL DE DECANATO
    TESORERIA_JEFE: 8, // JEFE DEL DEPARTAMENTO DE TESORERIA
    DCS: 9, // DECANATO DE CIENCIAS DE LA SALUD
    DCV: 10, // DECANATO DE CIENCIAS VETERINARIAS
    DAGRO: 11, // DECANATO DE AGRONOMÍA
    DCEE: 12, // DECANATO DE CIENCIAS ECONÓMICAS Y EMPRESARIALES
    DCYT: 13, // DECANATO DE CIENCIAS Y TECNOLOGÍA
    DIC: 14, // DECANATO DE INGENIERÍA CIVIL
    CARORA: 15, // NÚCLEO DE CARORA
    TOCUYO: 16, // NÚCLEO DE TOCUYO
    DEHA: 17, // DECANATO EXPERIMENTAL DE HUMANIDADES Y ARTES
    CARNET: 18, // CARNETIZACIÓN
    TESORERIA_ANALISTA: 19, // ANALISTA DEL DEPARTAMENTO DE TESORERÍA
    BN_ANA_UNI: 20, // ANALISTA DE UNIDAD DE BIENES NACIONALES
    BN_JEFE_UNI: 21, // JEFE DE UNIDAD DE BIENES NACIONALES
    BN_DIR_UNI: 22, // DIRECTOR DE UNIDAD DE BIENES NACIONALES
    BN_ANA_BIE: 23, // ANALISTA DE BIENES NACIONALES
    BN_JEFE_BIE: 24, // JEFE DE BIENES NACIONALES
} as const;

export type AT_ROLES = (typeof AT_ROLES)[keyof typeof AT_ROLES];

/* Cryptographic and Random Generation Constants */
export const AT_ALPHANUMERIC = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
export const AT_NUMERIC = '0123456789';

/* Validation Messages */
export const AT_PASSWORD_CRITERIA_MSG = 'La clave no cumple con los criterios mínimos de seguridad: debe tener entre 8 y 30 caracteres, e incluir al menos una letra, un número y un carácter especial o símbolo.';
