// @ts-nocheck
import { BaseService } from '@bases/service.base.js';
import { Database } from '@database/index.js';
import { ValidationError } from '@errors/validation.error.js';
import { DatabaseError } from '@errors/database.error.js';
import { AuthError, ForbiddenError, NotFoundError } from '@errors/index.js';
import { type ProcessedQueryFilters } from '@rules/api-query.type.js';
import { type ModelWithAssociate } from '@database/models/bases/sequelize.model.js';
import { type SequelizeRepositoryBase } from '@database/repositories/bases/sequelize.repository.js';
import { toKebabCase } from '@utils/string-formatters.util.js';
import { WhereOperators } from '@bases/repository.base.js';

class BasicTablesService extends BaseService {
    private catalogsSchema: Map<string, any> = new Map();
    private catalogRepoNames: Map<string, string> = new Map();

    constructor() {
        super();
        this.initializeCache();
    }

    private initializeCache(): void {
        const models = Database.getDefaultConnector().getModels<ModelWithAssociate>();

        for (const [modelName, model] of models.entries()) {
            if (model.isBasicTable) {
                const schema = this.extractSchema(model);
                const catalogName = model.appRawName || modelName;

                this.catalogsSchema.set(catalogName, {
                    modelName,
                    schema,
                    uiName: (model as any).uiName || catalogName,
                    associations: model.associations,
                    publicAccess: model['publicAccess'] || false,
                    private: model['private'] || false,
                });

                const baseName = (model.name || '').replace(/Model$/, '');
                const repoName = toKebabCase(baseName);
                this.catalogRepoNames.set(catalogName, repoName);
            }
        }
    }

    private extractSchema(model: ModelWithAssociate): Record<string, any> {
        const rawAttributes = model.getAttributes ? model.getAttributes() : (model as any).rawAttributes;
        const schema: Record<string, any> = {};

        const associations = model.associations || {};
        const foreignKeysMap = new Map<string, any>();

        for (const [alias, assoc] of Object.entries(associations)) {
            if ((assoc as any).associationType === 'BelongsTo') {
                const fk = typeof (assoc as any).foreignKey === 'string' ? (assoc as any).foreignKey : (assoc as any).foreignKey?.name;
                const targetModel = (assoc as any).target;
                const targetCatalogName = targetModel.appRawName || targetModel.name;
                const displayField = targetModel.config?.()?.displayField || targetModel.instance?.displayField || targetModel.displayField;
                if (fk) {
                    foreignKeysMap.set(fk, { target: targetCatalogName, alias, displayField });
                }
            }
        }

        let currentOrder = 1;
        const originalDefinition = typeof (model as any).definition === 'function' ? (model as any).definition() : {};

        for (const [key, attr] of Object.entries(rawAttributes)) {
            const typedAttr = attr as any;
            const originalDef = originalDefinition[key] || {};
            const enhancedData = originalDef.enhancedData || typedAttr.enhancedData || {};

            const uiLabel = enhancedData.uiLabel || key;
            const visible = enhancedData.visible !== false;

            const isAutoGenerated = typedAttr.primaryKey === true || ['id', 'createdAt', 'updatedAt', 'deletedAt'].includes(key);
            const editable = isAutoGenerated ? false : enhancedData.editable !== false;
            const isRequired = isAutoGenerated ? false : enhancedData.required !== undefined ? enhancedData.required : typedAttr.allowNull === false;

            let type = 'string';
            if (typedAttr.type) {
                const attrType = typedAttr.type.constructor.name.toLowerCase();
                if (attrType.includes('integer') || attrType.includes('bigint')) type = 'integer';
                else if (attrType.includes('decimal') || attrType.includes('float') || attrType.includes('real')) type = 'decimal';
                else if (attrType.includes('date') || attrType.includes('time')) type = 'date';
                else if (attrType.includes('boolean')) type = 'boolean';
            }

            const fieldSchema: any = {
                uiLabel,
                visible,
                editable,
                isRequired,
                type,
                private: enhancedData['private'] || false,
                order: enhancedData.order !== undefined ? enhancedData.order : currentOrder++,
                inputType: enhancedData.inputType,
                placeholder: enhancedData.placeholder,
                tooltip: enhancedData.tooltip,
            };

            if (foreignKeysMap.has(key)) {
                const fkInfo = foreignKeysMap.get(key);
                fieldSchema.relatedCatalog = fkInfo.target;
                fieldSchema.associationAlias = fkInfo.alias;
                if (fkInfo.displayField) {
                    fieldSchema.displayField = fkInfo.displayField;
                }
            } else if (typedAttr.references) {
                const refModel = typeof typedAttr.references === 'string' ? typedAttr.references : typedAttr.references.model?.tableName || typedAttr.references.model;
                fieldSchema.relatedCatalog = refModel;
            }

            if (foreignKeysMap.has(key)) {
                const relData = foreignKeysMap.get(key);
                if (relData?.displayField) {
                    fieldSchema.displayField = relData.displayField;
                }
            }

            schema[key] = fieldSchema;
        }

        return schema;
    }

    public getCatalogMetadata(catalogName: string, session: any): Record<string, any> {
        this.checkPermission(session, 'READ', catalogName, true);
        const catalog = this.catalogsSchema.get(catalogName);
        if (!catalog) throw new ValidationError(`Catálogo ${catalogName} no encontrado`);

        return catalog.schema;
    }

    public getAvailableCatalogs(filters?: ProcessedQueryFilters, session?: any): any {
        const catalogs = Array.from(this.catalogsSchema.entries())
            .filter(([name, catalog]) => {
                if (catalog['private']) {
                    if (!session) return false;
                    const perms = (session.permissions || []).map((p: string) => p.toUpperCase());
                    return perms.includes(`CRUD:READ:${name.toUpperCase()}`);
                }
                return true;
            })
            .map(([name, catalog]) => ({
                name,
                uiName: catalog.uiName,
                endpoint: `/api/v1/catalogs/${name}`,
            }));

        if (!filters || !filters.pagination) return catalogs;

        const { limit, offset } = filters.pagination;
        const total = catalogs.length;
        const data = catalogs.slice(offset, limit ? offset + (limit ?? 0) : total);

        return {
            data,
            total,
            limit,
            offset,
        };
    }

    private getRepository(catalogName: string): SequelizeRepositoryBase<any, any> {
        const repoName = this.catalogRepoNames.get(catalogName);
        if (!repoName) throw new ValidationError(`Catálogo ${catalogName} no encontrado`);

        return Database.repository('main', repoName) as SequelizeRepositoryBase<any, any>;
    }

    private getModelAssociations(catalogName: string): Record<string, any> | undefined {
        const catalog = this.catalogsSchema.get(catalogName);
        if (!catalog) throw new ValidationError(`Catálogo ${catalogName} no encontrado`);

        return catalog.associations;
    }

    private buildRelations(catalogName: string, include?: boolean): any[] | undefined {
        if (!include) return undefined;

        const associations = this.getModelAssociations(catalogName);
        if (!associations) return undefined;

        const relations: any[] = [];
        for (const [alias, assoc] of Object.entries(associations)) {
            const targetModel = (assoc as any).target;
            const attributes = [targetModel.primaryKeyAttribute];

            const rawAttrs = targetModel.getAttributes ? targetModel.getAttributes() : targetModel.rawAttributes;
            if (rawAttrs['name']) attributes.push('name');
            if (rawAttrs['description']) attributes.push('description');
            if (rawAttrs['descripcion']) attributes.push('descripcion');

            relations.push({
                association: alias,
                attributes,
                required: false,
            });
        }
        return relations;
    }

    private getVisibleAttributes(catalogName: string, session?: any): string[] {
        const catalog = this.catalogsSchema.get(catalogName);
        if (!catalog) throw new ValidationError(`Catálogo ${catalogName} no encontrado`);
        const schema = catalog.schema;
        const visibleAttrs = Object.entries(schema)
            .filter(([_, field]: [string, any]) => field.visible && (!field['private'] || session))
            .map(([key]) => key);
        if (!visibleAttrs.includes('id')) visibleAttrs.unshift('id');
        if (schema['deletedAt'] && !visibleAttrs.includes('deletedAt')) visibleAttrs.push('deletedAt');
        return visibleAttrs;
    }

    private sanitizeBody(catalogName: string, body: Record<string, any>, isUpdate: boolean = false): Record<string, any> {
        const catalog = this.catalogsSchema.get(catalogName);
        if (!catalog) throw new ValidationError(`Catálogo ${catalogName} no encontrado`);
        const schema = catalog.schema;
        const cleanBody: Record<string, any> = {};
        const missingFields: string[] = [];

        for (const [key, field] of Object.entries(schema)) {
            const f = field as any;

            if (f.editable && body[key] !== undefined) cleanBody[key] = body[key];
            else if (!isUpdate && f.isRequired && f.editable) missingFields.push(key);
        }

        if (missingFields.length > 0) throw new ValidationError('Campos requeridos no enviados', { missingFields } as any);

        return cleanBody;
    }

    private handleError(error: any): never {
        if (error.name === 'SequelizeForeignKeyConstraintError')
            throw new ValidationError('No puedes eliminar este registro porque está siendo utilizado en otras partes del sistema.', { cause: error } as any);

        if (error instanceof DatabaseError) throw new ValidationError(error.message, { cause: error } as any);

        throw error as Error;
    }

    private checkPermission(session: any, action: string, catalogName: string, isGet: boolean = false): void {
        const catalog = this.catalogsSchema.get(catalogName);
        if (!catalog) throw new ValidationError(`Catálogo ${catalogName} no encontrado`);

        if (isGet) {
            if (catalog['publicAccess']) return; // Legacy property support
            if (!catalog['private']) return; // Public by default if not private
        }

        if (!session) throw new AuthError('No autorizado para acceder a este catálogo', { code: 'NO_SESSION_FOR_CATALOG' });

        // BYPASS GLOBAL PARA SUPERADMIN
        const isSuperAdmin = session.roles?.some((r: any) => r.code === 'SUPERADMIN');
        if (isSuperAdmin) {
            return;
        }

        const perms = (session.permissions || []).map((p: string) => p.toUpperCase());
        const requiredPerm = `CRUD:${action}:${catalogName.toUpperCase()}`;

        if (!perms.includes(requiredPerm)) {
            throw new ForbiddenError(`No tienes permisos para ${action.toLowerCase()} en el catálogo ${catalogName}`);
        }
    }

    public async list(catalogName: string, filters: ProcessedQueryFilters, include: boolean, includeDeleted: boolean = false, session: any): Promise<any> {
        this.checkPermission(session, 'READ', catalogName, true);
        const repo = this.getRepository(catalogName);
        let relations = this.buildRelations(catalogName, include) || [];
        const attributes = this.getVisibleAttributes(catalogName, session);

        const catalog = this.catalogsSchema.get(catalogName);
        const schema = catalog?.schema || {};
        const associations = catalog?.associations || {};

        if (filters.qc) {
            for (const key of Object.keys(filters.qc)) {
                const condition = filters.qc[key];

                if (schema[key] && schema[key].relatedCatalog && schema[key].associationAlias) {
                    const alias = schema[key].associationAlias;

                    delete filters.qc[key];

                    let rel = relations.find((r) => r.association === alias);
                    if (!rel) {
                        rel = { association: alias, attributes: [], required: true };
                        relations.push(rel);
                    } else {
                        rel.required = true;
                    }

                    const assoc = associations[alias];
                    if (assoc) {
                        const targetModel = (assoc as any).target;
                        const rawAttrs = targetModel.getAttributes ? targetModel.getAttributes() : targetModel.rawAttributes;
                        const orConditions: any[] = [];

                        const likeCondition = typeof condition === 'string' ? { [WhereOperators.contains]: condition } : condition;

                        if (rawAttrs['name']) orConditions.push({ name: likeCondition });
                        if (rawAttrs['description']) orConditions.push({ description: likeCondition });
                        if (rawAttrs['descripcion']) orConditions.push({ descripcion: likeCondition });

                        if (orConditions.length > 0) {
                            rel.where = { [WhereOperators.or]: orConditions };
                        } else {
                            rel.where = { [targetModel.primaryKeyAttribute]: condition };
                        }
                    }
                } else if (schema[key] && schema[key].type === 'string' && typeof condition === 'string') {
                    filters.qc[key] = { [WhereOperators.contains]: condition };
                }
            }
        }

        const options: any = {
            ...filters,
            attributes,
        };

        if (relations.length > 0) {
            options.relations = relations;
        }

        try {
            return includeDeleted ? await repo.getAllIncludingDeleted(options, filters.qc) : await repo.getAll(options, filters.qc);
        } catch (error) {
            this.handleError(error);
        }
    }

    public async getById(catalogName: string, id: string | number, include: boolean, includeDeleted: boolean = false, session: any): Promise<any> {
        this.checkPermission(session, 'READ', catalogName, true);
        const repo = this.getRepository(catalogName);
        const relations = this.buildRelations(catalogName, include);
        const attributes = this.getVisibleAttributes(catalogName, session);

        try {
            return includeDeleted ? await repo.getByIdIncludingDeleted(id, { relations, attributes } as any) : await repo.getById(id, { relations, attributes } as any);
        } catch (error) {
            this.handleError(error);
        }
    }

    public async create(catalogName: string, body: Record<string, any>, session: any): Promise<any> {
        this.checkPermission(session, 'CREATE', catalogName);
        if ('id' in body) delete body.id;

        const cleanBody = this.sanitizeBody(catalogName, body, false);
        const repo = this.getRepository(catalogName);

        try {
            return await repo.create(cleanBody);
        } catch (error) {
            this.handleError(error);
        }
    }

    public async update(catalogName: string, id: string | number, body: Record<string, any>, session: any): Promise<any> {
        this.checkPermission(session, 'UPDATE', catalogName);
        const cleanBody = this.sanitizeBody(catalogName, body, true);
        const repo = this.getRepository(catalogName);

        try {
            await repo.update(id, cleanBody);
            return await repo.getById(id);
        } catch (error) {
            this.handleError(error);
        }
    }

    public async remove(catalogName: string, id: string | number, session: any): Promise<boolean> {
        this.checkPermission(session, 'DELETE', catalogName);
        const repo = this.getRepository(catalogName);

        try {
            const affectedRows = await repo.delete(id);
            if (!affectedRows) {
                throw new NotFoundError('El recurso no existe');
            }
            return true;
        } catch (error) {
            this.handleError(error);
        }
    }

    public async restore(catalogName: string, id: string | number, session: any): Promise<boolean> {
        this.checkPermission(session, 'RESTORE', catalogName);
        const repo = this.getRepository(catalogName);

        try {
            const affectedRows = await repo.restore(id);
            if (!affectedRows) {
                throw new NotFoundError('El recurso no existe o no estaba eliminado');
            }
            return true;
        } catch (error) {
            this.handleError(error);
        }
    }
}

export default new BasicTablesService();
